### ISSUE TITLE
Generator creates invalid dynamic_field for Nested object

### ISSUE THREAD

**Issue by vladaman** [angel-dart/serialize#36]
Following Model generates invalid dynamic_field 

```
@Serializable(autoIdAndDateFields: false)
abstract class _ApiUserResponse implements ApiGenericResponse {
  @override
  String status;

  @override
  String error;

  User user;
}
```
generates:
```

class ApiUserResponse extends _ApiUserResponse {
  ApiUserResponse({this.status, this.error, this.user});

  @override
  final String status;

  @override
  final String error;

  @override
  final dynamic user; // error here
```

![screenshot from 2018-07-12 17-12-26](https://user-images.githubusercontent.com/907206/42642402-1944dcf4-85f7-11e8-9aa9-3210c68f6ce3.png)

**Comment by thosakwe** [comment]
This is expected behavior, and also *not* an issue with `package:angel_serialize`.

It is mentioned in the documentation [here](https://github.com/angel-dart/serialize#nesting), this is what it says:

> If your model (`Author`) depends on a model defined in another file (`Book`), then you will need to generate `book.g.dart` before, `author.g.dart`, in a **separate build action**. This way, the analyzer can resolve the `Book` type.

When `build_runner` is generating files, if both `_User` and `_ApiUserResponse` are declared in the same build step, then there is no way the Dart analyzer will be able to know what a `User` is, because it hasn't been generated yet.

Instead, you must use `build.yaml` to declare separate steps:

```yaml
targets:
  _standalone_models:
   sources:
     - lib/src/models/user.dart
  $default:
   dependencies:
     - ":_standalone_models"
   sources:
     - lib/src/models/api_user_response.dart
```
